//! Diffs `remove()` against PNGs generated by the installed Python rembg.
//!
//! Regenerate the references with `python3 tests/gen_reference.py`. Outputs
//! are not expected to be bit-identical (PIL and `image` resize with different
//! arithmetic, onnxruntime builds differ), so each case is compared with a
//! mean/max tolerance instead.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use image::DynamicImage;
use rembg_rs::{remove_bytes, RemoveOptions, Session};
use serde::Deserialize;

/// Largest tolerated mean absolute difference, per channel out of 255.
///
/// The pipeline itself matches Python bit for bit when fed identical pixels
/// (see the stage tests in `src/matting.rs`); what is left is runtime noise:
/// PIL and `image` resize with different arithmetic (mean 0.17 on 8-bit
/// input), JPEG decoders round differently, and the two onnxruntime builds
/// disagree by ~0.2 mean on the predicted mask. Alpha matting amplifies that,
/// because a one-level mask change moves the trimap boundary.
const MEAN_TOL: f64 = 2.5;
/// A channel off by more than this counts as a "big" difference.
const BIG_TOL: i32 = 32;
/// Largest tolerated share of channels counted as big.
const BIG_FRAC_TOL: f64 = 0.01;

#[derive(Deserialize)]
struct Case {
    name: String,
    model: String,
    input: String,
    #[serde(default)]
    alpha_matting: bool,
    #[serde(default = "fg")]
    alpha_matting_foreground_threshold: u8,
    #[serde(default = "bg")]
    alpha_matting_background_threshold: u8,
    #[serde(default = "erode")]
    alpha_matting_erode_size: usize,
    #[serde(default)]
    only_mask: bool,
    #[serde(default)]
    post_process_mask: bool,
    #[serde(default)]
    decontaminate: bool,
    #[serde(default)]
    bgcolor: Option<[u8; 4]>,
}

fn fg() -> u8 {
    240
}
fn bg() -> u8 {
    10
}
fn erode() -> usize {
    10
}

impl Case {
    fn options(&self) -> RemoveOptions {
        RemoveOptions {
            alpha_matting: self.alpha_matting,
            alpha_matting_foreground_threshold: self.alpha_matting_foreground_threshold,
            alpha_matting_background_threshold: self.alpha_matting_background_threshold,
            alpha_matting_erode_size: self.alpha_matting_erode_size,
            only_mask: self.only_mask,
            post_process_mask: self.post_process_mask,
            decontaminate: self.decontaminate,
            bgcolor: self.bgcolor,
        }
    }
}

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests")
}

#[test]
fn matches_python_references() {
    let tests = root();
    let cases: Vec<Case> =
        serde_json::from_str(&fs::read_to_string(tests.join("cases.json")).unwrap()).unwrap();

    let mut sessions: HashMap<String, Session> = HashMap::new();
    let mut report = String::new();
    let mut failures = Vec::new();

    for case in &cases {
        let reference_path = tests.join("reference").join(format!("{}.png", case.name));
        let reference = match fs::read(&reference_path) {
            Ok(bytes) => bytes,
            Err(_) => {
                failures.push(format!(
                    "{}: missing reference (run `python3 tests/gen_reference.py`)",
                    case.name
                ));
                continue;
            }
        };

        let session = sessions
            .entry(case.model.clone())
            .or_insert_with(|| Session::new(&case.model).expect("model loads"));
        let input = fs::read(tests.join("assets").join(&case.input)).unwrap();

        let got = remove_bytes(&input, session, &case.options()).expect("remove succeeds");
        let stats = compare(&image::load_from_memory(&got).unwrap(), &reference);
        report.push_str(&format!(
            "{:<34} mean {:>7.4}  max {:>3}  big {:>6.3}%\n",
            case.name,
            stats.0,
            stats.1,
            stats.2 * 100.0
        ));
        if stats.0 > MEAN_TOL || stats.2 > BIG_FRAC_TOL {
            failures.push(format!(
                "{}: mean {:.4} > {MEAN_TOL}, big fraction {:.4} > {BIG_FRAC_TOL}",
                case.name, stats.0, stats.2
            ));
        }
    }

    print!("{report}");
    assert!(failures.is_empty(), "\n{}", failures.join("\n"));
}

/// `image`'s Lanczos3 against PIL's LANCZOS on the same pixels: the resize
/// floor under every later stage.
#[test]
fn resize_matches_pil() {
    let tests = root();
    let img = image::open(tests.join("reference").join("am_image.png")).unwrap();
    let want = image::open(tests.join("reference").join("resize320.png"))
        .expect("reference missing; run `python3 tests/gen_reference.py`")
        .to_rgb8();
    let got = image::imageops::resize(
        &img.to_rgb8(),
        320,
        320,
        image::imageops::FilterType::Lanczos3,
    );

    let mut sum = 0u64;
    let mut max = 0i32;
    for (pa, pb) in got.pixels().zip(want.pixels()) {
        for c in 0..3 {
            let d = (pa.0[c] as i32 - pb.0[c] as i32).abs();
            sum += d as u64;
            max = max.max(d);
        }
    }
    let n = (320u64 * 320 * 3) as f64;
    let mean = sum as f64 / n;
    println!("resize: mean {mean:.4} max {max}");
    assert!(mean < 0.5 && max < 32, "mean {mean} max {max}");
}

/// Mask parity on pixels Python decoded itself, so this measures only resize
/// and onnxruntime, not the JPEG decoder.
#[test]
fn predicted_mask_matches_python() {
    let tests = root();
    let img = image::open(tests.join("reference").join("am_image.png")).unwrap();
    let want = image::open(tests.join("reference").join("am_mask.png"))
        .expect("reference missing; run `python3 tests/gen_reference.py`")
        .to_luma8();

    let mut session = Session::new("u2net").unwrap();
    let got = session.predict(&img).unwrap();
    let (mean, max) = compare_luma(&got, &want);
    println!("u2net mask: mean {mean:.4} max {max}");
    assert!(mean < 1.0 && max < 32, "mean {mean} max {max}");
}

fn compare_luma(a: &image::GrayImage, b: &image::GrayImage) -> (f64, i32) {
    assert_eq!(a.dimensions(), b.dimensions(), "size differs");
    let mut sum = 0u64;
    let mut max = 0i32;
    for (pa, pb) in a.pixels().zip(b.pixels()) {
        let d = (pa.0[0] as i32 - pb.0[0] as i32).abs();
        sum += d as u64;
        max = max.max(d);
    }
    (sum as f64 / (a.width() as u64 * a.height() as u64) as f64, max)
}

/// (mean absolute difference, largest single-channel difference, share of
/// pixel-channels off by more than [`BIG_TOL`]).
fn compare(got: &DynamicImage, reference: &[u8]) -> (f64, i32, f64) {
    let reference = image::load_from_memory(reference).unwrap();
    assert_eq!(
        (got.width(), got.height()),
        (reference.width(), reference.height()),
        "output size differs from the reference"
    );

    let a = got.to_rgba8();
    let b = reference.to_rgba8();
    let mut sum = 0u64;
    let mut max = 0i32;
    let mut big = 0u64;
    for (pa, pb) in a.pixels().zip(b.pixels()) {
        for c in 0..4 {
            let d = (pa.0[c] as i32 - pb.0[c] as i32).abs();
            sum += d as u64;
            max = max.max(d);
            if d > BIG_TOL {
                big += 1;
            }
        }
    }
    let n = (a.width() as u64 * a.height() as u64 * 4) as f64;
    (sum as f64 / n, max, big as f64 / n)
}
